[build]
  command = "hugo --themesDir ../../"
  base    = ""
  publish = "public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.55.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
 # previous contents:
 #[build]
 # command = "hugo"
 # publish = "public"

#[build.environment]
#  HUGO_VERSION = "0.53"
#  HUGO_ENABLEGITINFO = "true"

#[context.production.environment]
#  HUGO_ENV = "production"
